# Server Message Protocol types
S_INIT = "SERVER_INIT"
S_LOGIN_FAIL = "LOGIN_FAIL"
S_LOGIN_SUCCESS = "LOGIN_SUCCESS"
S_TEXT = "TEXT"

# S_G_START = "GAME_START"

S_G_SYNC = "GAME_SYNC"

S_EXIT_NORMAL_QUEUE_SUCCESS = "EXIT_NORMAL_QUEUE_SUCCESS"

# Client Message Protocol types
C_TRY_LOGIN = "TRY_LOGIN"
C_TEXT = "TEXT"

C_IN_GAME_EXIT = "IN_GAME_TEXT"
C_GAME = "GAME_MSG"
C_G_SYNC = "GAME_SYNC"
C_JOIN_NORMAL_GAME = "JOIN_NORMAL_GAME"
C_EXIT_NORMAL_QUEUE = "EXIT_NORMAL_QUEUE"

C_GAME_ACTION = "GAME_ACTION"
